"""добавили признак публикации

Revision ID: 826ad7108926
Revises: d6763a38a14b
Create Date: 2024-04-25 20:37:07.578642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826ad7108926'
down_revision: Union[str, None] = 'd6763a38a14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image1', sa.LargeBinary(), nullable=True))
    op.add_column('products', sa.Column('image2', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image2')
    op.drop_column('products', 'image1')
    # ### end Alembic commands ###
