"""все также попытки

Revision ID: de2c33a19ed8
Revises: 90100f02d8b9
Create Date: 2024-04-25 19:13:34.998399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2c33a19ed8'
down_revision: Union[str, None] = '90100f02d8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image1',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'image2',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image2',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.alter_column('products', 'image1',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
